# Generated by Django 4.2 on 2025-02-17 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="coefficient",
        ),
    ]
