# Generated by Django 4.2 on 2025-02-17 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0007_matiere_coefficient"),
        ("grades", "0003_remove_note_coefficient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="matiere",
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="classes.matiere",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="note",
            name="assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignment_notes",
                to="grades.assignment",
            ),
        ),
    ]
