# Generated by Django 4.2 on 2025-02-18 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0004_remove_note_matiere_assignment_note_assignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignment_notes",
                to="grades.assignment",
            ),
        ),
    ]
