# Generated by Django 4.2 on 2025-03-05 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("classes", "0007_matiere_coefficient"),
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="presence",
            name="student",
        ),
        migrations.AddField(
            model_name="presence",
            name="person",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="presence",
            name="recorded_by",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marked_attendance",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="presence",
            name="classe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="classes.classe",
            ),
        ),
        migrations.AlterField(
            model_name="presence",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "Présent"),
                    ("late", "Late"),
                    ("absent", "Absent"),
                ],
                max_length=10,
            ),
        ),
    ]
