# Generated by Django 4.2 on 2025-02-16 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classe",
            name="professor",
            field=models.ForeignKey(
                limit_choices_to={"role": "professor"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes_taught",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
