# Generated by Django 4.2 on 2025-02-16 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("classes", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classe",
            name="professor",
        ),
        migrations.AddField(
            model_name="matiere",
            name="professor",
            field=models.ForeignKey(
                default=5,
                limit_choices_to={"role": "professor"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matieres",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
