# Generated by Django 4.2 on 2025-02-16 19:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("classes", "0004_alter_matiere_professor"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="matiere",
            unique_together={("name", "classe", "professor")},
        ),
    ]
