# Generated by Django 4.2 on 2025-02-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0005_alter_matiere_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="matiere",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="matiere",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="matiere",
            unique_together={("name", "classe")},
        ),
    ]
