# Generated by Django 4.2 on 2025-02-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0006_alter_matiere_unique_together_alter_matiere_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="matiere",
            name="coefficient",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
