# Generated by Django 4.2 on 2025-03-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("supervisor", "Supervisor"),
                    ("professor", "Professor"),
                    ("student", "Student"),
                    ("parent", "Parent"),
                ],
                max_length=10,
            ),
        ),
    ]
